#%RAML 1.0 DataType

type: object
displayName: ExchangeCredentials
properties:
  exchange:
    enum: [Bitstamp, Karken, CoinBase.Pro, Huobi, Bitfinex]
  userId: 
    type: string
    description: Exchange account user id (according to the exchange rewuirements)
    required: false
  key: string
  secret: string