#%RAML 1.0 DataType

type: object
displayName: OrderStatus
properties: 
  startTime: datetime
  elapsedTimeMinutes: number
  assetPair: string
  status:
    enum: ["Failed", "Done", "In-Progress"]
  requestedSize: number
  executionSize:
    type: number
    description: Size executed so far.
  executedTargerAmmount:
    type: number
    description: The ammount of the target asset executed so far.
  executionMessage?: string
  tradeOrderId: string

