#%RAML 1.0 DataType

type: object
displayName: SentOrder
properties: 
  account: string
  actionType: string
  currencyToAvailable: number
  currencyFromAvailable: number
  size: number
  assetPair: string
  exchange: string
  exchangeOrderId?: string
  tradeOrderId: string
  parentOrderId?: string
  childOrders?: SentOrder[]
  userId?: string
  orderTime: datetime
  price: number
  status: string
  timedOrder?: boolean
  ask: number
  bid: number