#%RAML 1.0
title: smart trader rest api between front end and back end
####################### getUserData ################################ 

/sendOrder:
  post:
    description: Send an order to be executed on the exchange(s). When a price isn't sent the order is executed as a market order.
    body:
      application/json:
        type: object
        required: true
        properties: 
          exchanges : 
            type: string[]  
            required: true 
          actionType: 
            type: string
            enum: ["buy_making", "sell_making", "buy", "sell"]
            required: true
          size: 
            type: number
            required: true
          assetPair: 
            type: string
            required: true
          price: 
            type: number
            required: false
          durationMinutes: 
            type: number
            required: false
          maxOrderSize: 
            type: number
            required: false
          externalOrderId: 
            type: string
            required: false
          userQuotePrice: 
            type: number
            required: false
          userId: 
            type: string
            required: false



/exchange/{exchange}:
  /accountBalance: 
    get:


  ####################### login ################################       
  /login: 
    post:
      description: 
      body:
        application/json:
          type: object
          required: true
          properties: 
            key : 
              type: string
              required: true 
            secret : 
              type: string
              required: true 
            clientId : 
              type: string
              required: false 

  /buyImmediateOrCancel: 
    post:
      description: 
      body:
        application/json:
          type: object
          required: true
          properties: 
            exchange : 
              type: string
              required: true 
            amount : 
              type: string
              required: true 
            price : 
              type: string
              required: true 
            currencyPair : 
              type: string
              required: false 

  /sellImmediateOrCancel: 
    post:
      description: 
      body:
        application/json:
          type: object
          required: true
          properties: 
            exchange : 
              type: string
              required: true 
            amount : 
              type: string
              required: true 
            price : 
              type: string
              required: true 
            currencyPair : 
              type: string
              required: false 

  /timeBuyTaking: 
    post:
      description: 
      body:
        application/json:
          type: object
          required: true
          properties: 
            exchange : 
              type: string
              required: true 
            amount : 
              type: string
              required: true 
            price : 
              type: string
              required: true 
            currencyPair : 
              type: string
              required: false 
            duration : 
              type: string
              required: true 
            maxOrderSize : 
              type: string
              required: true 

  /timedBuyMaking:
    post:
      description: 
      body:
        application/json:
          type: object
          required: true
          properties: 
            exchange :
              type: string
              required: true 
            amount : 
              type: string
              required: true 
            price : 
              type: string
              required: true 
            currencyPair : 
              type: string
              required: false 
            duration : 
              type: string
              required: true 
            maxOrderSize : 
              type: string
              required: true 
                    

          

  /timedSellMaking:
    post:
      description: 
      body:
        application/json:
          type: object
          required: true
          properties: 
            exchange : 
              type: string
              required: true 
            amount : 
              type: string
              required: true 
            price : 
              type: string
              required: true 
            currencyPair : 
              type: string
              required: false 
            duration : 
              type: string
              required: true 
            maxOrderSize : 
              type: string
              required: true 


