#%RAML 1.0
---

post:
  description: Create a new account
  body:
    application/json:
      type: object
      properties: 
        name: string
        description?: string
  responses:
    200:
      body: 
        type: object
        properties: 
          accountName: string
          description?: string


/{accountName}:
  put:
    description: Update existing account details
    body:
      application/json:
        type: object
        properties:
          description?: string
    responses:
      200:
        body: 
          type: AccountBalance

  /balance:
    get:
      description: Gets the balance of the account
      responses:
        200:
          body:
            type: AccountBalance
            example:
                  {
                    "totalBalance":
                      {
                        "USD": 
                          {
                            "confirmed": 1600,
                            "pendingDeposit": 0,
                            "pendingWithdrawal": 6850
                          },
                        "BTC":
                          {
                            "confirmed": 2500,
                            "pendingDeposit": 7000,
                            "pendingWithdrawal": 0
                          },
                        "BCH":
                          {
                            "confirmed": 8750,
                            "pendingDeposit": 5400,
                            "pendingWithdrawal": 0
                          }             
                      }            
                  }            

  /funds: !include funds.raml
  /trades: !include trades.raml