#%RAML 1.0
---

/withdrawals:
  post:
    description: Request to withdrawal amount of asset from Smart-Trader account.
    body:
      application/json:
        type: object
        properties:
          assetType: string 
          amount: number
    responses:
      200:
        body:
          type: object
          properties:
            transactionId : string
            assetType: string 
            amount: number
            requestTime: datetime
          example:
              {
                "transactionId": "FDSGDFHT15DS",
                "assetType": "USD", 
                "amount": 2000000,
                "requestTime": 2018-10-10 11:37:13.384
              }
      400:
        body:
          type: object
          properties:
            assetType: string 
            amount: number
            requestTime: datetime
            errorMessage: string
          example:
              {
                "assetType": "USD", 
                "amount": 2000000,
                "requestTime": 2018-10-10 11:37:13.384,
                "errorMessage": "Insufficient funds."
              }
  get:       
    description: List recent withdrawals request history.
    queryParameters:
      index?:
        description: Set page starting index.
        type: number
      size?:
        description: Set page size.
        type: number
    responses:
      200:
        body:
          type: array
          items:
            type: WithdrawalStatus
          example:
            [
              {
                "account": "BTC.com",
                "transactionId": "FDSGDFHT15DS",
                "requestTime": 2017-03-20T23:39:05.651638+00:00,
                "amount": 1500,
                "assetType": "USD",
                "status": "In-Progress"
              },
              {
                "account": "BTC.com",
                "transactionId": "HDS54SDGDGD",
                "requestTime": 2018-09-03 14:32:47.906,
                "amount": 2750,
                "assetType": "USD",
                "status": "Done"
              }
            ]

  /{transactionId}:
    get:       
      description: Returns a specific withdrawal transaction status.
      responses:
        200:
          body:
            type: WithdrawalStatus
            example:
                {
                  "account": "BTC.com",
                  "transactionId": "FDSGDFHT15DS",
                  "requestTime": 2017-03-20T23:39:05.651638+00:00,
                  "amount": 1500,
                  "assetType": "USD",
                  "status": "In-Progress"
                }
              