#%RAML 1.0
---

post:
      description: Send an order to be executed on Smart-Trader. When a price isn't sent the order is executed as a market order.
      body:
        application/json:
          type: Order
          example: 
            { 
              "actionType": "sell",
              "size": 1001,
              "assetPair": "BTC-USD",
              "price": 6500,
              "durationMinutes": 600
            }
      responses:
        200:
          body:
            type: object
            properties: 
              tradeOrderId: string
              walletPlane: 
                type: array
                items:
                  type: object
                  properties:
                    walletAddress: string
                    amount: number
            example:
              {
                "actionType": "sell",
                "size": 1001,
                "assetPair": "BTC-USD",
                "tradeOrderId": "ABC2D",
                "walletPlane": 
                  [
                    {
                      "walletAddress": "bc1qdp9q0lae7vz9vn4drw4e48kqkk44sccp34008s",
                      "amount": 750
                    },
                    {
                      "walletAddress": "rj5qdp9q0lae7vz9vn4drw4e48kqkk44sccp34118s",
                      "amount": 251
                    }
                  ]
              }

        400:
          body:
            type: object
            properties:
              assetType: string 
              amount: number
              requestTime: datetime
              errorMessage: string
            example:
                {
                  "actionType": "sell",
                  "size": 1001,
                  "assetPair": "BTC-USD",
                  "errorMessage": "Insufficient funds."
                }
get:       
  description: List recent orders history.
  queryParameters:
    index?:
      description: Set page starting index.
      type: number
    size?:
      description: Set page size.
      type: number
  responses:
    200:
      body:
        type: array
        items:
          type: OrderStatus
        example:
          [
            {
              "account": "BTC.com",
              "startTime": 2018-10-10 10:05:13.384,
              "elapsedTimeMinutes": 15.42,
              "assetPair": "BTC-USD",
              "actionType": "sell",
              "status": "Done",
              "requestedSize": 1500,
              "requestedPrice": 6300,
              "executionSize": 1001,
              "executedTargetAmount": 850000,
              "tradeOrderId": "ABC2D",
              "walletPlane": 
                [
                  {
                    "walletAddress": "bc1qdp9q0lae7vz9vn4drw4e48kqkk44sccp34008s",
                    "amount": 750
                  },
                  {
                    "walletAddress": "rj5qdp9q0lae7vz9vn4drw4e48kqkk44sccp34118s",
                    "amount": 251
                  }
                ]
              },
              {
                "account": "BTC.com",
                "startTime": 2018-07-11 15:42:28.193,
                "elapsedTimeMinutes": 45.28,
                "assetPair": "BCH-EUR",
                "actionType": "sell",
                "status": "Done",
                "requestedSize": 1500,
                "requestedPrice": 500,
                "executionSize": 1001,
                "executedTargetAmount": 850000,
                "tradeOrderId": "ABC2D",
                "walletPlane": 
                  [
                    {
                      "walletAddress": "0x301DF4cC1049982D8c289d9134Cd302678946Dd8",
                      "amount": 750
                    },
                    {
                      "walletAddress": "0x258DH7aD8579982D8c289d9134Cd302678946Dd9",
                      "amount": 750
                    }
                  ]
              }
          ]
/{tradeOrderId}:
  get:
    responses:
      200:
        body:
          application/json:
            type: OrderStatus
            example:
              {
                "account": "BTC.com",
                "startTime": 2018-10-10 10:05:13.384,
                "elapsedTimeMinutes": 15.42,
                "assetPair": "BTC-USD",
                "actionType": "sell",
                "status": "Done",
                "requestedSize": 1500,
                "requestedPrice": 6300,
                "executionSize": 1001,
                "executedTargetAmount": 850000,
                "tradeOrderId": "ABC2D",
                "walletPlane": 
                  [
                    {
                      "walletAddress": "bc1qdp9q0lae7vz9vn4drw4e48kqkk44sccp34008s",
                      "amount": 750
                    },
                    {
                      "walletAddress": "rj5qdp9q0lae7vz9vn4drw4e48kqkk44sccp34118s",
                      "amount": 251
                    }
                  ]
              }