
#%RAML 1.0
---

get:
  description: gets the list of all of the users
  responses:
      200:
        body:
          type: array
          items:
            type: object
            properties:
              name: string
              description?: string
          
post:
  description: Create a new user
  body:
    application/json:
      type: User
  responses:
    200:
      body:
        type: object
        properties:
          name: string
          description?: string
        example:
          {
            "name": "Bob",
            "description": "Bob Rohan - Finances"
          }
put:
  description: Update an existing user details
  body:
    application/json:
      type: User
  responses:
    200:
      body:
        type: object
        properties:
          name: string
          description?: string
        example:
          {
            "name": "Bob",
            "description": "Bob Rohan - Finances"
          }
