#%RAML 1.0
---
title: Smart Trade
version: v0.8.2
protocols: [HTTPS]
mediaType: application/json
baseUri: https://smart-trader/{version}/
securedBy: [ passthrough ]
securitySchemes:
  passthrough: !include securitySchemas/passthrough.raml

types:
  AccountBalance: !include types/account_balance.raml
  Order: !include types/order.raml
  WithdrawalStatus: !include types/withdrawal_status.raml
  OrderStatus: !include types/order_status.raml
  ReportFilter: !include types/report_filter.raml
  ReportFilterTrades: !include types/report_filter_trades.raml
  SentOrder: !include types/sent_order.raml

/accounts: !include ./endpoints/accounts.raml 
/reports: !include ./endpoints/reports.raml